version: '2'
services:
  carsells-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/carsells/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carsells
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
